### PR TITLE
Update Azure Containerapps docs & script

### LINKED ISSUE #134: Azure super heroes is broken on new postgres change
The single script version for super heroes is broken on https://github.com/quarkusio/quarkus-super-heroes/blob/main/docs/deploying-to-azure-containerapps.md - there was a change for the protocol for postgres to include open telemetry and now the villains app cant connect to the database

Exception: 
error 11:12:08 ERROR traceId=, parentId=, spanId=, sampled= [or.hi.en.jd.sp.SqlExceptionHelper] (JPA Startup Thread: <default>) Driver does not support the provided URL: jdbc:postgresql://villains-db-codespace.postgres.database.azure.com:5432/villains?ssl=true&sslmode=require

### LINKED ISSUE #136: Use the TAG_SYSTEM variable when creating the container registry
When creating the Azure container registry, we should use the `TAG_SYSTEM` variable: `--tags system="$TAG_SYSTEM"` instead of ` --tags system=quarkus-super-heroes`

```
az acr create \
  --resource-group "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --name "$CONTAINER_REGISTRY_NAME" \
  --sku Standard \
  --tags system=quarkus-super-heroes
```

### PR DESCRIPTION
**Pull request by edeandrea**
Update to the Azure ContainerApps script and documentation.

Fixes #134
Fixes #136

### CODE REVIEW

**Comment by edeandrea** [comment]
@agoncal Would you mind taking a look please?

**Comment by edeandrea** [comment]
Fixes #134

**Comment by edeandrea** [comment]
Gentle ping @agoncal to take a look at this.

**Comment by edeandrea** [comment]
Almost done @agoncal. I ran into https://github.com/Azure/azure-cli-extensions/issues/5340 when I was trying to test it. I'll ping you once I've updated this PR.

**Comment by edeandrea** [comment]
@agoncal Changes are in - please review. If all looks good, please **Squash and merge**.

**Review by agoncal — APPROVED** [review]

**Pull request merged**
