### PR TITLE
Add a parent pom for IDEs

### LINKED ISSUE #7: Having a parent pom for IDEs
It would be nice to have a parent pom. It's not mandatory, but for some IDEs it's much easier to open the project and have all the modules setup.

### PR DESCRIPTION
**Pull request by agoncal**
Fix #7

### CODE REVIEW

**Review by edeandrea — COMMENTED** [review]
Don't you have to also include a reference to the parent in each of the child modules? I'm not so much a Maven person so I don't know.

**Comment by edeandrea** [comment]
I'll also have to check whether or not this breaks the automation

https://github.com/quarkusio/quarkus-super-heroes/blob/main/scripts/generate-k8s-resources.sh#L45-L67

**Comment by edeandrea** [comment]
Looks good. Thanks for the PR!

**Comment by agoncal** [comment]
We could include a reference to the parent pom in each child, but that couples the code a little bit. This way we "simulate" that all the projects are totally independent. I think it's better, it kind of says "you see, each microservice is totally independent from the others" ;o)

**Pull request merged**
