### PR TITLE
OpenTelemetryClientFilter is not required to be registered manually. The Vert.x client already adds the OpenTelemetry instrumentation.

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Comment by radcortez** [comment]
This fixes the in https://github.com/quarkusio/quarkus/issues/23612#issuecomment-1241533219.

But it seems there is another issue, which I don't think it is related with the OTel one:

```
  <java.lang.IllegalArgumentException: Invalid REST Client URL used: 'stork://villain-service/api/villains/random'
```

**Comment by edeandrea** [comment]
Is not needing the OtelClientFilter something new /recent? It was needed when I originally added the otel stuff in 2.10.

**Comment by edeandrea** [comment]
@radcortez when I test this with Quarkus 2.12.1, the `VillainClient` does not capture spans in the rest client call:

image

Was that change something that was introduced in 2.13?

When I build Quarkus main and run against that, I do see the

```
ERROR [or.jb.re.re.cl.ha.ClientSendRequestHandler] (vert.x-eventloop-thread-1) Invalid REST Client URL used: 'stork://villain-service/api/villains/random'
```

that you mentioned.

This seems to be a regression in Quarkus? The app uses stork, so the URL is correct (and has been working as `stork://villain-service` for some time now.

**Comment by radcortez** [comment]
> Is not needing the OtelClientFilter something new /recent? It was needed when I originally added the otel stuff in 2.10.

It should never be needed for the Reactive REST Client, because this is backed by Vert.x and the OpenTelemetry context is handled by the Vert.x Tracer. In the last version, we are not registering the `OpenTelemetryClientFilter` to avoid a double processing of the span. The classic client still requires the `OpenTelemetryClientFilter`. Maybe there is something that we overlooked, let me check.

> This seems to be a regression in Quarkus? The app uses stork, so the URL is correct and has been working as `stork://villain-service` for some time now.

I'm not aware, but I'll also check.

**Comment by edeandrea** [comment]
The Villain client isn't using the Reactive rest client. Just the standard jaxrs client

**Comment by edeandrea** [comment]
@radcortez If I do this

```java
public VillainClient(FightConfig fightConfig, OpenTelemetry openTelemetry) {
    this.villainClient = ClientBuilder.newClient()
      .register(new MicroProfileRestClientRequestFilter(new DefaultClientHeadersFactoryImpl()))
      .register(new OpenTelemetryClientFilter(openTelemetry))
      .target(fightConfig.villain().clientBaseUrl())
      .path("api/villains/");
  }
```

to inject the `OpenTelemetry` instance rather than the `OpenTelemetryClientFilter` and then create the `OpenTelemetryClientFilter`, then we get past the CDI injection exception. Now it moves onto the

```
Invalid REST Client URL used: 'stork://villain-service/api/villains/hello'
```

error.

My guess is something else changed and some other filter that was there previously is no longer there?

**Comment by edeandrea** [comment]
Adding onto my last comment

If I do 

```java
public VillainClient(FightConfig fightConfig, OpenTelemetry openTelemetry) {
    this.villainClient = ClientBuilder.newClient()
      .register(new MicroProfileRestClientRequestFilter(new DefaultClientHeadersFactoryImpl()))
      .register(new OpenTelemetryClientFilter(openTelemetry))
      .target(fightConfig.villain().clientBaseUrl())
      .path("api/villains/");
  }
```

Everything works fine with 2.12.2.Final. Once we get to 2.13, then it blows up with that Stork error.

**Comment by radcortez** [comment]
Ah, actually the span is generated, but the context is not propagated correctly, so it won't show up in the expected trace.

**Comment by edeandrea** [comment]
I don't think this will build because the `StorkClientRequestFilter` class doesn't exist until Quarkus 2.13...

**Comment by edeandrea** [comment]
Thanks @radcortez ! I'm building Quarkus main now and will test these changes locally

**Comment by radcortez** [comment]
Thanks! Let me know if there is any issue.

**Comment by edeandrea** [comment]
I can confirm it works built against Quarkus main

image

**Comment by edeandrea** [comment]
Thank you again for the help!

**Pull request merged**
