### PR TITLE
Adding JMeter scripts for load testing

### LINKED ISSUE #77: What about adding JMeter load test?
@edeandrea  What about having a JMeter load test that gets new fighters and just fights? This way we could add some load (and Azure Load Testing is compatible with JMeter load scripts ;o)

WDYT ?

### PR DESCRIPTION
**Pull request by agoncal**
Fixes #77

### CODE REVIEW

**Comment by edeandrea** [comment]
Couple of things

1. Should we move the jmeter stuff into a new subdirectory inside `scripts`? Feels kinda weird having a pom.xml alongside other shell scripts?

2. For the maven project should we provide the maven wrapper stuff to be consistent with the other projects?

**Comment by edeandrea** [comment]
On 1 more thing I thought of - are there things in the pom that should be kept up to date automatically by dependabot? If so, we should update the dependabot settings (.github/dependabot.yml`) with this PR.

That would also mean we'd need a GitHub action which tested that running Jeter via maven worked as expected.

**Comment by agoncal** [comment]
Yes, good idea to have the files under `scripts/jmeter`directory and having a Maven wrapper.

Well, the only thing to update is the version of JMeter Maven plugin (`<jmeter-plugin.version>3.5.0</jmeter-plugin.version>`). Do we want to have dependabot detect that ? It's not very critical to have an up to date version. You see. 

What do you mean by "GitHub action which tests that running JMeter via maven worked as expected". Do you want to just execute the `mvn jmeter:jmeter` goal (but because the application is not started, the load test will fail) or you want to bootstrap the entire app, and then execute JMeter with a running app ?

**Comment by edeandrea** [comment]
> What do you mean by "GitHub action which tests that running JMeter via maven worked as expected". Do you want to just execute the mvn jmeter:jmeter goal (but because the application is not started, the load test will fail) or you want to bootstrap the entire app, and then execute JMeter with a running app ?

If we don't care about keeping the jmeter plugin automatically up to date, then yeah this doesn't matter. If we do, then we'll need to be able to stand up the fights service (can do it on minikube if we want as part of the pipeline - I talk about bootstrapping minikube in https://kubebyexample.com/en/resources/automation/keeping-content-relevant). Once stood up (we could just do the fights service and wait for fallbacks) and then run jmeter with a simple load. Then we'd have to have a script or something that asserted the artifacts produced by jmeter were there (basic smoke test).

IDK if its worth all that - just throwing it out there to get your thoughts. Would be cool to have though!

**Comment by edeandrea** [comment]
Hey @agoncal I did some cleanup of your initial commit. What do you think?

**Comment by agoncal** [comment]
Yes, much better with the right doc and the Maven wrapper

**Pull request merged**
