### PR TITLE
Java 21

### LINKED ISSUE #376: Introduce Java 21
Now that Java 21 is out, run all of the automation & produce Java 17 & 21 images for all the apps.

One note is that the [Mandrel builder image](https://quay.io/repository/quarkus/ubi-quarkus-mandrel-builder-image?tab=tags&tag=latest) doesn't yet have a Java 21 image, so for now we'll have to use the [GraalVM CE builder image](https://quay.io/repository/quarkus/ubi-quarkus-graalvmce-builder-image?tab=tags)

### PR DESCRIPTION
**Pull request by edeandrea**
Convert to Java 21 baseline

Fixes #376

### CODE REVIEW

**Comment by gastaldi** [comment]
Looks like this PR is ready to go? What's missing?

**Comment by edeandrea** [comment]
We were holding off on making the switch to java 21 as a baseline. We did this PR shortly after java 21 came out, so it was thought it may be better to wait a bit. 

That being said, I'm totally open to revisiting it. This PR would need some updates since `main` has diverged a bit from this PR branch. But it's close.

**Comment by edeandrea** [comment]
@gastaldi I'm thinking that I will revisit this after RHBQ 3.15 ships. That way we have an rhbq-3.15 LTS branch with a Java 17 baseline and future versions can baseline on Java 21.

@cescoffier / @geoand  what do you think?

**Review by cescoffier — APPROVED** [review]

**Comment by edeandrea** [comment]
> @gastaldi I'm thinking that I will revisit this after RHBQ 3.15 ships. That way we have an rhbq-3.15 LTS branch with a Java 17 baseline and future versions can baseline on Java 21.
> 

Actually now that we have a `3.15.Final` branch with a Java 17 baseline I think I will move `main` to Java 21. When RHBQ 3.15 comes out it will be branched from the `3.15.Final` branch.

**Comment by edeandrea** [comment]
Since `main` has diverged so much since this PR was originally drafted, I'm going to close this in favor of #1234

**Pull request closed without merging**
