### PR TITLE
Creating hyperfoil benchmarks

### LINKED ISSUE #286: Switching from jmeter to hyperfoil
In the past few months, we have seen countless broken benchmarks.  Most of them were blindly using jmeter without understanding coordinated omission problems. Basically: do not trust jmeter. 

It would be great to switch to hyperfoil (which we can trust) instead of jmeter to avoid such a problem and have a place showing how to do it.

I'm sure @franz1981 would be happy to help on this one (as he has to explain the problem every time).

### PR DESCRIPTION
**Pull request by edeandrea**
First crack at creating some Hyperfoil benchmark files for the apps.

@cescoffier / @franz1981 / @geoand / @whitingjr would you mind taking a look?

@franz1981 I'm very open to feedback on these. Let me know if you'd like to get together for an hour or two.

Closes #286

### CODE REVIEW

**Comment by edeandrea** [comment]
@franz1981 / @whitingjr I do have a question though about the `ergonomics`. I have this in all of the benchmarks:

```yaml
#  Disable stopping the scenario on 4xx or 5xx response
ergonomics:
  autoRangeCheck: false
  stopOnInvalid: false
```

I originally figured that continuing the benchmark upon an error condition might be a good thing to do, but now I'm not so sure. What are your thoughts on this?

**Review by geoand — COMMENTED** [review]
Very nice!

I've never used `Hyperfoil` myself, so I can't add anything useful here

**Comment by edeandrea** [comment]
> I've never used `Hyperfoil` myself, so I can't add anything useful here

I know enough to be dangerous :)

**Comment by edeandrea** [comment]
@franz1981 would you mind taking a look at this when you get a free moment?

**Comment by whitingjr** [comment]
> 

Using ergonomics to disable status code checking is useful when the benchmark configuration intends to receive status codes outside the usual range (2xx or 3xx).
Whereas if all the operations are intended to return only 2xx then a benchmark run that is only receiving 5xx codes means there is something clearly wrong in the configuration and need fixing.

**Comment by edeandrea** [comment]
Thanks @whitingjr . I removed the ergonomics.

**Pull request merged**
