### PR TITLE
Rewrite UI in react

### LINKED ISSUE #290: Rewrite UI in a more modern framework
[@edeandrea asks](https://github.com/quarkusio/quarkus-super-heroes/issues/87#issuecomment-1554417456) "should we re-write the UI using something more modern (like React)? I thought I saw something internally where someone had done that already.

It would be nice to have a test suite for the UI so that we can turn on dependabot. There are also a few enhancements for the UI, but as it stands today, I don't really dare touch it with a 10 foot pole."

I'd love to see us move away from Angular so the UI is more maintainable, and we can add tests, and then, dependabit. I'm a +1 for either React, or an alternative like Lit.

### PR DESCRIPTION
**Pull request by edeandrea**
Taking quarkusio/quarkus-workshops#419 and bringing here.

@holly-cummins Could you take a look? I added the location stuff into it as well.

I couldn't get the `App.test.js` test to work because it doesn't seem to be waiting for the ajax calls to finish (which end up erroring out because there is no back end...).

I wasn't sure how to fix that, so I just commented out the test for now.

Fixes #290

### CODE REVIEW

**Comment by edeandrea** [comment]
@holly-cummins I'm also seeing the CI build fail...

```
22:06:12 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) > superheroes-ui@1.0 build
22:06:12 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) > react-scripts build
22:06:12 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) 
22:06:13 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) Creating an optimized production build...
22:06:16 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) One of your dependencies, babel-preset-react-app, is importing the
22:06:16 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) "@babel/plugin-proposal-private-property-in-object" package without
22:06:16 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) declaring it in its dependencies. This is currently working because
22:06:16 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) "@babel/plugin-proposal-private-property-in-object" is already in your
22:06:16 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) node_modules folder for unrelated reasons, but it may break at any time.
22:06:16 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) 
22:06:16 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) babel-preset-react-app is part of the create-react-app project, which
22:06:16 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) is not maintianed anymore. It is thus unlikely that this bug will
22:06:16 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
22:06:16 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) your devDependencies to work around this error. This will make this message
22:06:16 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) go away.
22:06:16 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38)   
22:06:20 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) 
22:06:20 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) Treating warnings as errors because process.env.CI = true.
22:06:20 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) Most CI servers set it automatically.
22:06:20 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) 
22:06:20 INFO  [io.qu.qu.de.pa.PackageManagerRunner] (build-38) Failed to compile.
```

I did add `@babel/plugin-proposal-private-property-in-object` to `devDependencies` like it suggests, but that didn't fix the error message.

Any thoughts/ideas?

**Comment by edeandrea** [comment]
I think I might have fixed it. Waiting for the next CI to run to verify.

**Review by holly-cummins — APPROVED** [review]
LGTM! I will see if I can reproduce the App.test.js issue locally.

**Comment by edeandrea** [comment]
My latest commit resurrects `App.test.js`

**Pull request merged**
