### PR TITLE
langchain4j integration

### LINKED ISSUE #368: Support native compilation in narration service
Currently due to microsoft/semantic-kernel#2885 the `rest-narration` service does not support native compilation. Once this issue is addressed on the Microsoft side, enable native compilation in the `rest-narration` service.

### LINKED ISSUE #421: Switch narration app to use quarkus-langchain4j
Currently the `rest-narration` application uses the [Microsoft Semantic Kernel for Java](https://devblogs.microsoft.com/semantic-kernel/introducing-semantic-kernel-for-java/) library for connecting to the OpenAI providers.

There are some drawbacks to using this library in Quarkus:
1. It does not support native compilation (see https://github.com/microsoft/semantic-kernel/issues/2885) 
2. It is "heavy" and is built on top of project reactor and not Java 9 Flows
3. It is very difficult to test. You can not use WireMock for mocking calls due to the fact the Azure client thats baked in requires the use of specific Microsoft certificates that aren't provided. Because of this we have to revert to object-based mocking, which means having to know/understand the internals of the Semantic Kernel library to know & understand how to mock it

Instead, we should use the [Quarkus Langchain4J extension](https://docs.quarkiverse.io/quarkus-langchain4j/dev/openai.html). This would also make it super easy to use a local LLM instead of invoking a remode instance. Its also more advanced than Semantic Kernel, has more functionality, the API is nicer (no project reactor), and it has a larger community behind it.

### PR DESCRIPTION
**Pull request by edeandrea**
Switch the narration app to use the quarkus-langchain4j extension instead of Microsoft Semantic Kernel.

Fixes #421 
Fixes #368

### CODE REVIEW

**Comment by edeandrea** [comment]
Need to wait for https://github.com/quarkiverse/quarkus-langchain4j/issues/149 and https://github.com/quarkiverse/quarkus-langchain4j/issues/148 to be incorporated into a release before merging this.

**Comment by edeandrea** [comment]
Waiting for https://github.com/quarkiverse/quarkus-langchain4j/issues/149 and https://github.com/quarkiverse/quarkus-langchain4j/pull/145 to be released and incorporated into this before merging.

**Comment by edeandrea** [comment]
@geoand Would you mind taking a look? You can focus on changes just in the `rest-narration` app.

**Review by geoand — APPROVED** [review]
LGTM

**Pull request merged**
