### PR TITLE
Cleanup pact consumer contract tests

### PR DESCRIPTION
**Pull request by edeandrea**
The current pact consumer contract tests in `rest-fights` really only test the mock and not any actual business functionality. We should change this so that the pact consumer contract mocks are used 1 layer up in the service tier.

### CODE REVIEW

**Comment by edeandrea** [comment]
@holly-cummins would you mind reviewing?

**Comment by holly-cummins** [comment]
LGTM!

**Review by holly-cummins — APPROVED** [review]

**Comment by edeandrea** [comment]
Sweet! I'll wait until the CI runs before merging.

**Comment by holly-cummins** [comment]
I don't think it's directly relevant, but your experiments with test ordering reminded me of this comment in one of my contract tests: 

```
 * Why does this class have a strange name? Good question.
 * There's some cross-talk between the tests, so that if this test runs, and takes more than a few milliseconds,
 * the NormalModeContractIT test fails. It fails with a message that the resources project's classes
 * can't be found ... even though the NormalModeContractIT test doesn't even use them.
 *
 * Changing this class so that the name doesn't start with Test works around the issue.
```

I originally called the class `TestModeContractTestIT`, then it was always breaking in puzzling ways, so I renamed it to `TtestModeContractTestIT`. That worked great except that every now and then I'd spot the typo, fix it, and then spend two hours debugging why my build had broken. So now it's [`TheTestModeContractTestIT`](https://github.com/quarkiverse/quarkus-pact/blob/main/quarkus-pact-provider/integration-tests/src/test/java/io/quarkiverse/pact/it/TheTestModeContractTestIT.java).

**Comment by edeandrea** [comment]
In my case the test class name is `FightServiceConsumerContractTests`. I'm really drawing straws now as to why some of the tests fail with bind errors.

I've looked through the Pact `PactConsumerTestExt` source code and in `afterTestExecution` it clearly closes & shuts down the mock server after each test.

Not sure why this is only an issue in GH actions and "works fine on my machine".

**Comment by edeandrea** [comment]
@holly-cummins if you [look at the latest failure](https://github.com/quarkusio/quarkus-super-heroes/actions/runs/4375662993/jobs/7656673871#step:4:1975) you'll see that only 5 of the tests failed with the bind error:

```
Error:  Errors: 
Error:    FightServiceConsumerContractTests.findRandomFightersHeroConsumerContract » Bind Address already in use
Error:    FightServiceConsumerContractTests.findRandomFightersHeroNotFoundHeroConsumerContract » Bind Address already in use
Error:    FightServiceConsumerContractTests.findRandomFightersNoneFoundHeroConsumerContract » Bind Address already in use
Error:    FightServiceConsumerContractTests.findRandomFightersVillainNotFoundHeroConsumerContract » Bind Address already in use
Error:    FightServiceConsumerContractTests.helloHeroesSuccess » Bind Address already in use
```

There are 10 total tests in the class, so half of them went and bound just fine.

**Comment by edeandrea** [comment]
Actually what's interesting is that its the 5 hero service mocks that are getting the bind error. I wonder if there's something on that port for some reason. Let me try a different port.

**Comment by edeandrea** [comment]
Looks like that was the problem! weird, because I used ports that the other apps use. Anyways I'm going to merge.

**Pull request merged**
