### PR TITLE
Introduce narration service

### LINKED ISSUE #361: Add a narration microservice that can narrate fights
Add a narration microservice that narrates fights using some AI intelligence, similar to what was done in quarkusio/quarkus-workshops#287.

This implementation will be a bit more generic. By default it should not try to connect to any AI service. The AI service should be configurable and needs to be specifically enabled due to api keys/cloud resources/etc that need to be created outside of this new application in order for it to function properly.

We will build in the Microsoft Semantic Kernel implementation, but it will need to be specifically enabled and configured. If not, a default message will be returned.

The code should also be structured in a way that other AI implementations can easily be added to the application and switched to over time.

### PR DESCRIPTION
**Pull request by edeandrea**
Add a narration microservice that narrates fights using some AI intelligence, similar to what was done in quarkusio/quarkus-workshops#287.

Some cleanup has been done here as well.
1. By default the integration with **ANY** OpenAI service is disabled. This is not free, and currently the Microsoft OpenAI integration is by invite only. We want the service to **ALWAYS** work
2. It is driven through configuration to be able to support additional OpenAI providers in the future (See the `NarrationConfig` class). At runtime the configuration can be adapted as additional providers are added
3. It is fully reactive (the workshop uses `block`. This uses the Mutiny <-> Reactor bridge to keep it fully reactive
4. The initialization of all the Microsoft Semantic Kernel stuff is done once at app startup, not on every request (as it is implemented in quarkusio/quarkus-workshops#287

Closes #361

### CODE REVIEW

**Comment by edeandrea** [comment]
@agoncal / @cescoffier / @geoand / @holly-cummins please take a look when you get a chance. Thanks!

**Comment by edeandrea** [comment]
One thing I did notice @agoncal is that compiling the narration service to native does not work. There are errors in the Microsoft Semantic Kernel stuff that need to be resolved I think. 

See https://github.com/quarkusio/quarkus-super-heroes/actions/runs/6226077340/job/16897830327?pr=365

**Review by agoncal — APPROVED** [review]
Nice. I liked a few things in your code (like initializing the client in the @PostConstruct or importing the skills from the classpath). I'll get some inspiration

**Comment by edeandrea** [comment]
@agoncal I created microsoft/semantic-kernel#2885

One question I had, though, was how do I express credentials in the semantic kernel API? It seems that on my machine I have to do an `az login` and then its using the current context or something? That won't work if I run in kube somewhere. I probably need a way to pass in Azure credentials somehow?

Or is that what the `key`/`endpoint`/`deployment name` is?

**Comment by edeandrea** [comment]
@agoncal as mentioned in our Zulip thread, the skill import by resources doesn't seem to work in SK version 0.2.8 unless you are running in dev mode.

I did clone & locally build the 0.2.9-SNAPSHOT version and I can say that everything works fine in both dev mode and when running via `java -jar`.

If we can plead for an SK 0.2.9-SNAPSHOT release sooner than later that would be awesome!

**Comment by agoncal** [comment]
@edeandrea  SK 0.2.9 release should happen this week. I'll let you know.

**Comment by agoncal** [comment]
@edeandrea SK 0.2.9 has been released: https://central.sonatype.com/artifact/com.microsoft.semantic-kernel/semantickernel-bom/0.2.9-alpha

**Comment by edeandrea** [comment]
@agoncal until microsoft/semantic-kernel#2885 is resolved I've disabled native for the `rest-narration` service. It will only be available in the JVM for now.

**Pull request merged**
